name: Testing to find workaround
on: [workflow_dispatch]

jobs:
  test-386:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26
          architecture: '386'
          cache: true
      - run: go version